name: packn_app
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase関連パッケージ（バージョンは確認済最新）
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.13.1

  # UIやユーティリティ
  cupertino_icons: ^1.0.2

  intl: ^0.18.1  # ← この行を追加

  image_picker: ^1.1.0
  firebase_storage: ^11.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/icons/
