name: packn_app
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0

  # Firebase関連パッケージ（バージョンは確認済最新）
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.13.1

  # UIやユーティリティ
  cupertino_icons: ^1.0.2

  intl: ^0.18.1  # ← この行を追加

  image_picker: ^1.1.0
  firebase_storage: ^11.6.4

  provider: ^6.1.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # ← ランチャーアイコンは dev_dependencies に置く
  flutter_launcher_icons: ^0.13.1

# ← ここはトップレベル（dependencies/flutter の “外側”）
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  # 必要に応じてアダプティブアイコンや名前を追加できます：
  # adaptive_icon_background: "#ffffff"  # or assets path
  # adaptive_icon_foreground: assets/images/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/icons/
    - assets/images/app_icon.png
