// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM31x3NVSv0d9S7l0KQRh0qV6yWjWhVMY',
    appId: '1:550720671500:web:13b982e7f2677178894329',
    messagingSenderId: '550720671500',
    projectId: 'packn-9fecd',
    authDomain: 'packn-9fecd.firebaseapp.com',
    storageBucket: 'packn-9fecd.firebasestorage.app',
    measurementId: 'G-G3EYHK8VMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuDSbzEuowSi5TAM6YT9qrtBEQ-uV1Q4',
    appId: '1:550720671500:android:dc585271921dabb1894329',
    messagingSenderId: '550720671500',
    projectId: 'packn-9fecd',
    storageBucket: 'packn-9fecd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1adonzsaEZfK5yfGQLZeOQQ-4H_pyqd0',
    appId: '1:550720671500:ios:fa23df72f30341df894329',
    messagingSenderId: '550720671500',
    projectId: 'packn-9fecd',
    storageBucket: 'packn-9fecd.firebasestorage.app',
    iosBundleId: 'com.example.packnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1adonzsaEZfK5yfGQLZeOQQ-4H_pyqd0',
    appId: '1:550720671500:ios:fa23df72f30341df894329',
    messagingSenderId: '550720671500',
    projectId: 'packn-9fecd',
    storageBucket: 'packn-9fecd.firebasestorage.app',
    iosBundleId: 'com.example.packnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM31x3NVSv0d9S7l0KQRh0qV6yWjWhVMY',
    appId: '1:550720671500:web:533eee1a9beb26e9894329',
    messagingSenderId: '550720671500',
    projectId: 'packn-9fecd',
    authDomain: 'packn-9fecd.firebaseapp.com',
    storageBucket: 'packn-9fecd.firebasestorage.app',
    measurementId: 'G-X0N5TQKN1R',
  );
}
